name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel black ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with Black
        run: black --check .

      - name: Lint with Ruff
        run: ruff check .

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Install package and check it works
        run: |
          pip install .
          gsc --help
